export const FETCH_ALL_RECIPES = 'FETCH_ALL_RECIPES';
export const FETCH_ALL_RECIPES_SUCCESS = 'FETCH_ALL_RECIPES_SUCCESS';
export const FETCH_ALL_RECIPES_FAIL = 'FETCH_ALL_RECIPES_FAIL';

export const FETCH_SINGLE_RECIPE = 'FETCH_SINGLE_RECIPE';
export const FETCH_SINGLE_RECIPE_SUCCESS = 'FETCH_SINGLE_RECIPE_SUCCESS';
export const FETCH_SINGLE_RECIPE_FAIL = 'FETCH_SINGLE_RECIPE_FAIL';

export const DELETE_RECIPE = 'DELETE_RECIPE';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAIL = 'DELETE_RECIPE_FAIL';

export const RESET_ALL_RECIPES = 'RESET_ALL_RECIPES';
export const RESET_SINGLE_RECIPE = 'RESET_SINGLE_RECIPE';
