export const FETCH_ALL_RECIPES = 'FETCH_ALL_RECIPES';
export const FETCH_ALL_RECIPES_SUCCESS = 'FETCH_ALL_RECIPES_SUCCESS';
export const FETCH_ALL_RECIPES_FAIL = 'FETCH_ALL_RECIPES_FAIL';

export const FETCH_SINGLE_RECIPE = 'FETCH_SINGLE_RECIPE';
export const FETCH_SINGLE_RECIPE_SUCCESS = 'FETCH_SINGLE_RECIPE_SUCCESS';
export const FETCH_SINGLE_RECIPE_FAIL = 'FETCH_SINGLE_RECIPE_FAIL';
